// generated by voice.py from narration.json and the spoken clips
const TIMING = [
 {
  "id": "title",
  "dur": 8.541666666666666,
  "lines": [
   {
    "start": 1.4,
    "end": 7.55,
    "text": "Every year, a public firm tells investors how it is doing, through two channels in one annual report."
   }
  ]
 },
 {
  "id": "channels",
  "dur": 14.375,
  "lines": [
   {
    "start": 0.6,
    "end": 7.448,
    "text": "Item 8, the financial statements, is strict. GAAP has a rule for almost every line, and auditors check it."
   },
   {
    "start": 7.898,
    "end": 13.376,
    "text": "Item 7, the MD&A, is management's own narrative. It is far more flexible."
   }
  ]
 },
 {
  "id": "fits",
  "dur": 8.083333333333334,
  "lines": [
   {
    "start": 0.5,
    "end": 6.888,
    "text": "For a factory-style firm, the statements work well: earnings and book value explain the stock price."
   }
  ]
 },
 {
  "id": "stuck",
  "dur": 14.541666666666666,
  "lines": [
   {
    "start": 0.6,
    "end": 7.645,
    "text": "But value built on ideas, software and brands doesn't fit GAAP's boxes. Price drifts away from the numbers."
   },
   {
    "start": 8.095,
    "end": 13.739,
    "text": "The authors call this financial statement inadequacy: one minus that R-squared."
   }
  ]
 },
 {
  "id": "question",
  "dur": 7.375,
  "lines": [
   {
    "start": 0.4,
    "end": 6.465,
    "text": "So what does the manager do? Just comply and move on, or turn to the flexible channel?"
   }
  ]
 },
 {
  "id": "mdna",
  "dur": 12.75,
  "lines": [
   {
    "start": 0.5,
    "end": 6.58,
    "text": "They turn. Firms with weaker statements discuss non-GAAP measures more, tailored to their own situation."
   },
   {
    "start": 7.03,
    "end": 11.561,
    "text": "And they write more forward-looking statements, so investors can see where the firm is heading."
   }
  ]
 },
 {
  "id": "numbers",
  "dur": 11.833333333333334,
  "lines": [
   {
    "start": 0.5,
    "end": 6.141,
    "text": "From the most to the least adequate firms, non-GAAP discussion rises by 19 percent,"
   },
   {
    "start": 6.591,
    "end": 10.216,
    "text": "and forward-looking sentences rise by about 5 percent."
   }
  ]
 },
 {
  "id": "methods",
  "dur": 17.291666666666668,
  "lines": [
   {
    "start": 0.5,
    "end": 8.073,
    "text": "The MD&As are read by machine. Keywords catch non-GAAP talk; a deep-learning network spots forward-looking sentences."
   },
   {
    "start": 8.523,
    "end": 16.279,
    "text": "TopicTiling cuts each document into topics. The extra disclosure appears where traditional reporting is weakest, such as intangibles."
   }
  ]
 },
 {
  "id": "mosaic",
  "dur": 8.416666666666666,
  "lines": [
   {
    "start": 0.5,
    "end": 7.008,
    "text": "So managers use their channels together, like a mosaic. When one is constrained, the other carries more."
   }
  ]
 },
 {
  "id": "end",
  "dur": 8.75,
  "lines": [
   {
    "start": 0.6,
    "end": 5.56,
    "text": "Brown, Hinson and Tucker, Contemporary Accounting Research, 2024."
   }
  ]
 }
];
