"""Voice the narration with the local Qwen3-TTS Base model (x-vector clone) and
derive the film's scene timing from the spoken lines.

    conda activate qwen3-tts
    python voice.py              # generate missing clips, then lay out the timeline
    python voice.py --regen      # regenerate every clip
    python voice.py --only 3 7   # regenerate clips 3 and 7 (global line numbers)

Writes out/voice/line_XX.wav, out/voice/narration.wav, out/voice/narration.srt
and timing.js, which the film loads: every scene lasts lead + lines + gaps + tail.
"""
import argparse
import json
from pathlib import Path

import numpy as np
import soundfile as sf

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = HERE / "out" / "voice"
FPS = 24
GAP = 0.45          # s between lines inside a scene
REF = ROOT / "film" / "voice" / "ref_clone.wav"


def trim(wav, sr, thresh=0.01, pad=0.05):
    idx = np.where(np.abs(wav) > thresh)[0]
    return wav if not len(idx) else wav[max(0, idx[0] - int(pad * sr)): idx[-1] + int(pad * sr)]


def srt_time(s):
    ms = int(round(s * 1000))
    return f"{ms // 3600000:02d}:{ms // 60000 % 60:02d}:{ms // 1000 % 60:02d},{ms % 1000:03d}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=str(ROOT / "Qwen3-TTS-12Hz-0.6B-Base"))
    ap.add_argument("--regen", action="store_true")
    ap.add_argument("--only", type=int, nargs="*")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    script = json.loads((HERE / "narration.json").read_text())
    lines = [ln for sc in script["scenes"] for ln in sc["lines"]]
    OUT.mkdir(parents=True, exist_ok=True)
    todo = [k for k in range(len(lines)) if args.regen or (args.only and k in args.only)
            or not (OUT / f"line_{k:02d}.wav").exists()]
    if todo:
        import torch
        from qwen_tts import Qwen3TTSModel
        model = Qwen3TTSModel.from_pretrained(
            args.model, device_map="cuda:0" if torch.cuda.is_available() else "cpu",
            dtype=torch.bfloat16, attn_implementation="sdpa")
        prompt = model.create_voice_clone_prompt(ref_audio=str(REF), ref_text=None, x_vector_only_mode=True)
        for k in todo:
            torch.manual_seed(args.seed + k)
            wavs, sr = model.generate_voice_clone(text=lines[k]["say"], language=script["language"],
                                                  voice_clone_prompt=prompt)
            wav = trim(np.asarray(wavs[0], dtype=np.float32), sr)
            sf.write(OUT / f"line_{k:02d}.wav", wav, sr)
            print(f"line {k:2d}: {len(wav) / sr:5.2f} s  {lines[k]['say']}")

    clips = [sf.read(OUT / f"line_{k:02d}.wav", dtype="float32") for k in range(len(lines))]
    sr = clips[0][1]
    timing, placed, t0, k = [], [], 0.0, 0
    for sc in script["scenes"]:
        t = sc["lead"]
        rows = []
        for j, ln in enumerate(sc["lines"]):
            d = len(clips[k][0]) / sr
            rows.append({"start": round(t, 3), "end": round(t + d, 3), "text": ln["text"]})
            placed.append((t0 + t, clips[k][0], ln["text"]))
            t += d + (GAP if j < len(sc["lines"]) - 1 else 0)
            k += 1
        dur = round((t + sc["tail"]) * FPS) / FPS
        timing.append({"id": sc["id"], "dur": dur, "lines": rows})
        t0 += dur

    track = np.zeros(int(t0 * sr) + 1, dtype=np.float32)
    srt = []
    for n, (s, wav, text) in enumerate(placed):
        a = int(s * sr)
        track[a:a + len(wav)] += wav[: len(track) - a]
        srt.append(f"{n + 1}\n{srt_time(s)} --> {srt_time(s + len(wav) / sr)}\n{text}\n")
    track *= 0.89 / max(1e-6, np.abs(track).max())
    sf.write(OUT / "narration.wav", track, sr)
    (OUT / "narration.srt").write_text("\n".join(srt))
    (HERE / "timing.js").write_text("// generated by voice.py from narration.json and the spoken clips\n"
                                   "const TIMING = " + json.dumps(timing, indent=1) + ";\n")
    for sc in timing:
        print(f"{sc['id']:<9} {sc['dur']:6.2f} s  " + "  ".join(f"[{r['start']:.2f}-{r['end']:.2f}]" for r in sc["lines"]))
    print(f"total {t0:.2f} s")


if __name__ == "__main__":
    main()
